spring.devtools.livereload.enabled: true
spring.freemarker.cache: false
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: "%a %{X-Forwarded-For}i %u %t \"%r\" %s %b %Dms"
      directory: ./logs/
    basedir: .

logging:
  file:
    name: ./logs/anymeal.log
  level:
    root: debug
    com.hanatour: debug
    io.netty: info
    javax.management: info
    jdk.event.security: info
    org.apache: info
    org.hibernate: info
    org.springframework: info
    springfox: info
    sun.rmi: info
    Validator: info
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 10