spring.devtools.livereload.enabled: true
spring.freemarker.cache: false
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: "%a %{X-Forwarded-For}i %u %t \"%r\" %s %b %Dms"
      directory: ./logs/
    basedir: .

logging:
  file:
    name: ./logs/anymeal.log
  level:
    root: debug
    com.hanatour: debug
  logback:
    rollingpolicy:
      max-file-size: 500MB
      max-history: 10