spring.devtools.livereload.enabled: true
spring.freemarker.cache: false
server:
  port: 8080
  tomcat:
    accesslog:
      enabled: true
      pattern: "%a %{X-Forwarded-For}i %u %t \"%r\" %s %b %Dms"
      directory: ./logs/
    basedir: .

anymeal:
  kakao-restapi-key: # Inject by environment variable
  default-longitude: "126.983618"
  default-latitude: "37.572043"