# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build -Danymeal.kakao-restapi-key=${{ secrets.KAKAO_RESTAPI_KEY }}

    - name: Stop service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDR }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY}}
        script: |
          pkill -f any-meal-0.0.1 || true

    - name: Deploy to instance
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: "./build/libs/"
        REMOTE_HOST: ${{ secrets.SERVER_ADDR }}
        REMOTE_USER: "ubuntu"
        TARGET: "/home/ubuntu/any-meal"

    - name: Start service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDR }}
        username: ubuntu
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          setsid nohup java -jar \
          -Danymeal.kakao-restapi-key=${{ secrets.KAKAO_RESTAPI_KEY }} \
          ~/any-meal/any-meal-0.0.1-SNAPSHOT.jar &>~/any-meal/any-meal.out &
        
