# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: Stop service
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: pkill -f any-meal
        host: ${{ secrets.SERVER_ADDR }}
        username: ec2-user
        privateKey: ${{ secrets.EC2_SSH_KEY}}
    - name: Deploy to my EC2 instance
      uses: easingthemes/ssh-deploy@main
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        SOURCE: "./build/libs/"
        REMOTE_HOST: ${{ secrets.SERVER_ADDR }}
        REMOTE_USER: "ec2-user"
        TARGET: "/home/ec2-user/any-meal"
    - name: Start service
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SERVER_ADDR }}
        username: ec2-user
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          setsid nohup java -jar ~/any-meal/any-meal-0.0.1-SNAPSHOT.jar &>~/any-meal/any-meal.out &
        
